### PR TITLE
fix error

### PR DESCRIPTION
**Pull request by BilikoX**
Preserve Real-Ip when not accessed through cloudflare

### CODE REVIEW

**Comment by mrinc** [comment]
@Amadeus331 See build status, linting failed for complexity.  

It would break normal behavour, so let's rather make it an optional config option and split into seperate statement.

**Comment by mrinc** [comment]
*We also must add tests for this change

**Comment by BilikoX** [comment]
> @Amadeus331 See build status, linting failed for complexity.
> 
> It would break normal behavour, so let's rather make it an optional config option and split into seperate statement.

It's my fault. I shouldn't have added the local IP to trustIP. Now close PR

**Comment by BilikoX** [comment]
> > @Amadeus331 See build status, linting failed for complexity.
> > It would break normal behavour, so let's rather make it an optional config option and split into seperate statement.
> 
> It's my fault. I shouldn't have added the local IP to trustIP. Now close PR

 When the request comes from a trusted proxy other than of cloudflare, there is still a problem

**Comment by BilikoX** [comment]
> > > @Amadeus331 See build status, linting failed for complexity.
> > > It would break normal behavour, so let's rather make it an optional config option and split into seperate statement.
> > 
> > 
> > It's my fault. I shouldn't have added the local IP to trustIP. Now close PR
> 
> When the request comes from a trusted proxy other than of cloudflare, there is still a problem

I resubmitted the pull request, and it passed the test this time.
https://github.com/BetterCorp/cloudflarewarp/pull/24#issue-1709835578

**Pull request closed without merging**
